In [ ]:
#cài đặt
# !pip install numpy

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [4]:
type(arr1)

numpy.ndarray

In [ ]:
arr2 = np.array(range(10)) # np.arrange(10)
arr2 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2[2] = 100
arr2

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [8]:
arr2[2] = 3.14
arr2

array([0, 1, 3, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr2.dtype = 'float32'
arr2[2] = 3.14
arr2 

array([0.0000000e+00, 0.0000000e+00, 3.1400001e+00, 0.0000000e+00,
       1.2644384e+11, 2.1424999e+00, 4.2038954e-45, 0.0000000e+00,
       5.6051939e-45, 0.0000000e+00, 7.0064923e-45, 0.0000000e+00,
       8.4077908e-45, 0.0000000e+00, 9.8090893e-45, 0.0000000e+00,
       1.1210388e-44, 0.0000000e+00, 1.2611686e-44, 0.0000000e+00],
      dtype=float32)

In [12]:
0.1 + 0.1 + 0.1 == 0.3

False

In [13]:
arr1 

array([1, 2, 3])

In [14]:
arr1[:2]

array([1, 2])

In [18]:
arr1 = np.array([1,2,3])
sub_arr = arr1[:2]
arr1[:2] = [0,0]
arr1

array([0, 0, 3])

In [19]:
alist = [1,2,3]
sub_list = alist[:2] 
sub_list = [0,0]
alist

[1, 2, 3]

In [20]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[:,0] +arr2d[0,:]

array([ 2,  6, 10])

In [31]:
arr2d[0] +arr2d

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [30]:
arr2d[0] + 5

array([6, 7, 8])

In [28]:
arr2d[0]+arr2d[1]

array([5, 7, 9])

In [27]:
arr2d[0,:]

array([1, 2, 3])

In [26]:
arr2d[0]

array([1, 2, 3])

In [24]:
arr2d[1,2]

np.int64(6)

In [25]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [21]:
list2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]

In [23]:
list2d[0][1]

2